#!/bin/bash

# Update the package list
apt-get update -y

# Install Nginx
apt-get install -y nginx

# Create a custom HTML file with the required content
echo "Holberton School" > /var/www/html/index.nginx-debian.html

# Restart Nginx without using systemctl
service nginx restart
